version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  testes:
    docker:
      # replace with your preferred image
      - image: cimg/ruby:2.7.6
    steps:
      - browser-tools/install-browser-tools:
          install-chrome: true 
          install-chromedriver: true 
      - checkout
      - run:
          name: install bundler
          command: "sudo gem install bundler"
      - run:
          name: install-dependencies
          command: "sudo bundle install"
      - run:
          name:  ls 1
          command: "ls" 
      - run:
          name:  capybara
          command: "cd Capybara"
      - run:
          name:  ls 2
          command: "ls" 
workflows:
  example-workflow:
    jobs:
      -   testes